### ISSUE TITLE
Not Disabling Defender or Merging to Registry 

### ISSUE THREAD

**Issue by ginger007tb** [disable-windows-defender/disable-windows-defender.github.io#2]
I Tried To Run Disable_Windows_Defender_on_windows_10.reg in Administrator with Registry Editor

It was working for awhile I don't now what happen was there a recent update from windows that

it not allowing this action I hate restriction.

**Comment by jfcherng** [comment]
https://github.com/disable-windows-defender/disable-windows-defender.github.io#disable-windows-defender-on-windows-10

**Comment by Calinou** [comment]
As stated at the top of the page, this approach of disabling Windows Defender via the registry is no longer supported in recent Windows 10 versions.

I've created a pinned issue for this: https://github.com/disable-windows-defender/disable-windows-defender.github.io/issues/3
